---
- name: Ensure vector directory exists
  ansible.builtin.file:
    path: "{{ vector_path }}"
    state: directory
    mode: "0755"
- name: Donwload and unpack Vector archive
  ansible.builtin.unarchive:
    src: https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-{{ vector_arch }}-unknown-linux-musl.tar.gz
    remote_src: true
    dest: "{{ vector_path }}"
    extra_opts:
      - --strip-components=2
    creates: "{{ vector_path }}/bin"
- name: Vector to systemd
  become: true
  ansible.builtin.copy:
    src: "{{ vector_path }}/etc/systemd/vector.service"
    dest: /etc/systemd/system/
    remote_src: true
    mode: preserve
- name: Update environment for vector | Update profile
  ansible.builtin.lineinfile:
    path: "$HOME/.bash_profile"
    search_string: "export PATH"
    line: "export PATH=\"{{ vector_path }}/bin:$PATH\""
- name: Configure Vector | Ensure config directory exists
  ansible.builtin.file:
    path: "{{ vector_config_path }}"
    state: directory
    mode: "0755"
- name: Configure Vector | Template config
  ansible.builtin.template:
    src: vector.toml.j2
    mode: "0644"
    dest: "{{ vector_config_path }}/vector.toml"

  changed_when: false
  register: vector
- name: Vector stdout
  ansible.builtin.debug:
    var: vector.stdout